name: Deploy to Host

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    #- name: Create .env file
    #  run: |
    #    touch .env.local
    #    echo VITE_xxx=${{ secrets.xxx }} >> .env.local
    - run: npm ci
    - run: npm run package --if-present
    - name: Scp package to host
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "build.tar.gz"
        target: "/arc/caddy/site"
    - name: Ssh to host and reload
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          sudo su
          cd /arc/caddy/site
          tar -xvf build.tar.gz && rm -rf website && mv build website
          ls website/
          rm -rf build.tar.gz build
          cd ..
          sh ./reload.sh
        
